-- 테이블 삭제
DROP TABLE CUSTOMER;
DROP TABLE BANK;

-- 테이블 생성
CREATE TABLE BANK(
    BANK_CODE VARCHAR2(20 BYTE) NULL,
    BANK_NAME VARCHAR2(30 BYTE) NULL
);

-- 테이블 생성
CREATE TABLE CUSTOMER(
    CUS_NO    NUMBER            NULL,
    CUS_NAME  VARCHAR2(30 BYTE) NOT NULL,
    CUS_PHONE VARCHAR2(20 BYTE) NULL UNIQUE,   -- 유니크
    CUS_AGE   NUMBER            NULL CONSTRAINT CK_CUS_AGE CHECK(CUS_AGE BETWEEN 0 AND 100),
    BANK_CODE VARCHAR2(20 BYTE) NULL
);


-- 기본키 추가
ALTER TABLE BANK
    ADD CONSTRAINT PK_BANK PRIMARY KEY(BANK_CODE);

ALTER TABLE CUSTOMER
    ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUS_NO);
    
-- 외래키 추가
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMER_BANK FOREIGN KEY(BANK_CODE)
        REFERENCES BANK(BANK_CODE);