/*
    수강신청
    1. 여러 학생이 여러 과목을 신청하는 다대다관계
    2. 학생-과목의 직접적인 다대다관계 설정은 불가능
    3. 학생-수강신청-과목으로 일대다관계 2개 설정으로 진행
    
    참고. 외래키 제약조건을 무시하고 테이블 삭제
    순서에 상관없이 삭제할 수 있음
    DROP TABLE STUDENT CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT CASCADE CONSTRAINTS;
    DROP TABLE REQUEST CASCADE CONSTRAINTS;
*/


DROP TABLE REQUEST;   -- 수강신청 테이블
DROP TABLE SUBJECT; -- 과목 테이블
DROP TABLE STUDENT; -- 학생 테이블

-- 학생테이블
CREATE TABLE STUDENT(
    STU_NO CHAR(5 BYTE) NOT NULL,
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE NUMBER(3) NOT NULL,
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO)
);

-- 과목 테이블
CREATE TABLE SUBJECT(
    SUB_CODE CHAR(5 BYTE) NOT NULL,
    SUB_NAME VARCHAR2(20 BYTE) NULL,
    SUB_PRO VARCHAR2(20 BYTE) NULL,
    CONSTRAINT PK_SUBJECT PRIMARY KEY(SUB_CODE)
);
    
-- 수강신청 테이블
CREATE TABLE REQUEST(
    REQ_NO NUMBER(2) NOT NULL,
    STU_NO CHAR(5 BYTE) NOT NULL,
    SUB_CODE CHAR(5 BYTE) NOT NULL,
    CONSTRAINT PK_REQUEST PRIMARY KEY(REQ_NO),
    CONSTRAINT FK_REQUEST_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT(STU_NO),
    CONSTRAINT FK_REQUEST_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE)
);
    
