-- 테이블 삭제
DROP TABLE CUSTOMER;
DROP TABLE BANK;

-- 테이블 생성
CREATE TABLE BANK(
    BANK_CODE VARCHAR2(20 BYTE) NOT NULL,
    BANK_NAME VARCHAR2(30 BYTE) NOT NULL
);

-- 테이블 생성
CREATE TABLE CUSTOMER(
    NO    NUMBER            NOT NULL,
    NAME  VARCHAR2(30 BYTE) NOT NULL,
    PHONE VARCHAR2(20 BYTE) UNIQUE,   -- 유니크
    AGE   NUMBER            CHECK(AGE BETWEEN 0 AND 100),
    BANK_CODE VARCHAR2(20 BYTE) 
);


-- 기본키 추가
ALTER TABLE BANK ADD CONSTRAINT PK_BANK PRIMARY KEY(BANK_CODE);
ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(NO);
    
-- 외래키 추가
ALTER TABLE CUSTOMER
    ADD CONSTRAINT FK_CUSTOMER_BANK FOREIGN KEY(BANK_CODE)
        REFERENCES BANK(BANK_CODE)
            ON DELETE cascade;
        
-- 테이블 변경하기(ALTER TABLE)

-- 1. BANK 테이블에 BANK_PHONE 칼럼을 추가하시오.