DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE PROFESSOR;
DROP TABLE COURSE;

-- 1. 학번 테이블
CREATE TABLE STUDENT(
    STU_NO      NUMBER(5)          NOT NULL,
    STU_NAME    VARCHAR2(20 BYTE)  NULL,
    STU_ADDS    VARCHAR2(100 BYTE) NULL,
    STU_LEV     NUMBER(1)          NULL,
    PRO_NO      NUMBER(5)          NOT NULL
);

-- 2. 교수 테이블
CREATE TABLE PROFESSOR(
    PRO_NO    NUMBER(5)         NOT NULL,
    PRO_NAME  VARCHAR2(20 BYTE) NULL,
    PRO_MAJOR VARCHAR2(25 BYTE) NULL
);

-- 3. 과목 테이블
CREATE TABLE COURSE(
    COU_NO    NUMBER(5)         NOT NULL,
    COU_NAME  VARCHAR2(20 BYTE) NULL,
    COU_SCORE NUMBER(3,2)       NULL
);

-- 4. 수강신청 테이블
CREATE TABLE ENROLL(
    ENR_NO NUMBER(5) NOT NULL,
    STU_NO NUMBER(5) NOT NULL,
    COU_NO NUMBER(2) NOT NULL,
    ENR_DATE DATE    NULL
);

-- 5. 강의 테이블
CREATE TABLE LECTURE(
    LEC_NO   NUMBER(5)         NOT NULL,
    PRO_NO   NUMBER(5)         NOT NULL,
    ENR_NO   NUMBER(5)         NOT NULL,
    LEC_NAME VARCHAR2(25 BYTE) NULL,
    LEC_ROOM VARCHAR2(15 BYTE) NULL
);

-- 기본키 지정
ALTER TABLE STUDENT   ADD CONSTRAINT PK_STUDENT   PRIMARY KEY(STU_NO);
ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NO);
ALTER TABLE COURSE    ADD CONSTRAINT PK_COURSE    PRIMARY KEY(COU_NO);
ALTER TABLE ENROLL    ADD CONSTRAINT PK_ENROLL    PRIMARY KEY(ENR_NO);
ALTER TABLE LECTURE   ADD CONSTRAINT PK_LECTURE   PRIMARY KEY(LEC_NO);

-- 외래키 지정
ALTER TABLE ENROLL ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO)
    REFERENCES STUDENT(STU_NO)
        ON DELETE CASCADE;
ALTER TABLE ENROLL ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COU_NO)
    REFERENCES COURSE(COU_NO)
        ON DELETE CASCADE;
ALTER TABLE LECTURE ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENR_NO)
    REFERENCES ENROLL(ENR_NO)
        ON DELETE SET NULL;
ALTER TABLE LECTURE ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(PRO_NO)
    REFERENCES PROFESSOR(PRO_NO)
        ON DELETE SET NULL;
ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY(PRO_NO)
    REFERENCES PROFESSOR(PRO_NO)
        ON DELETE SET NULL;
        
    
