-- 시퀀스
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
-- 캐시를 사용하면 번호가 간혹 점프해서 나온다

-- 테이블
DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO    NUMBER                  NOT NULL,
    TITLE            VARCHAR2(100 BYTE) NOT NULL,
    CONTENT      VARCHAR2(400 BYTE),
    CREATE_DATE DATE,
    CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NO)
);

-- 행
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '공지1', '불났다1', SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '공지2', '불났다2', SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '공지3', '불났다3', SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '공지4', '불났다4', SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '공지5', '불났다5', SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, '공지6', '불났다6', SYSDATE);
COMMIT;